/**
 * Brainstormer Brainstorm Template
 *
 * The markdown template structure for brainstorm files generated by Brainstormer.
 * Includes options, recommendations, and optional notes/research sections.
 */

export const BRAINSTORMER_BRAINSTORM_TEMPLATE = `## Brainstorm File Structure

Generate brainstorm file to: \`.sisyphus/drafts/brainstorms/{name}.md\`

\`\`\`markdown
# Brainstorm: {Topic}

**Generated**: {timestamp}
**Purpose**: Quick ideation before deep planning

---

## Quick Summary

> **Goal**: {1-2 sentence summary of what we're brainstorming}
> **Context**: {Brief context - what triggered this brainstorm}
> **Options Generated**: {N options}

---

## Options

### Option 1: {Title}
- **What**: {One-line description}
- **Why it could work**: {One-line rationale}
- **Risk/Tradeoff**: {One-line risk or tradeoff}
- **Effort**: {Quick | Short | Medium | Large}

### Option 2: {Title}
- **What**: {One-line description}
- **Why it could work**: {One-line rationale}
- **Risk/Tradeoff**: {One-line risk or tradeoff}
- **Effort**: {Quick | Short | Medium | Large}

### Option 3: {Title}
- **What**: {One-line description}
- **Why it could work**: {One-line rationale}
- **Risk/Tradeoff**: {One-line risk or tradeoff}
- **Effort**: {Quick | Short | Medium | Large}

{number more options as needed...}

---

## Recommendation

**Top Choice**: Option {N} - {Title}

**Rationale**:
- {Key reason 1}
- {Key reason 2}
- {Key reason 3}

**Second Choice**: Option {N} - {Title} (if applicable)

---

## Assumptions

- {Assumption 1}
- {Assumption 2}

## Open Questions

- {Question 1 - what we don't know}
- {Question 2 - what needs user input}

## Constraints to Validate

- {Constraint 1}
- {Constraint 2}

---

## Next Steps

To convert to a work plan:
1. Select an option above
2. Use \`/start-planning\` command
3. Or request "Create the work plan" to escalate to Prometheus

---

## Notes (Optional)

*Add any additional context, research findings, or observations here.*

---

## Research (Optional)

*If research was conducted during brainstorm, document key findings here.*

### Sources
- {Source 1}
- {Source 2}

### Key Findings
- {Finding 1}
- {Finding 2}

---
`